/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VeriSocialProfile } from "./VeriSocialProfile";
export type { VeriSocialWorldID } from "./VeriSocialWorldID";
export * as factories from "./factories";
export { VeriSocialProfile__factory } from "./factories/VeriSocialProfile__factory";
export { VeriSocialWorldID__factory } from "./factories/VeriSocialWorldID__factory";
